name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build page
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          yarn install
          yarn run build
      - name: Pages Commit & Publish
        run: |
          cd docs/.vitepress/dist
          touch .nojekyll
          git init
          git add -A        
          git commit -m "publish site"
          git push -f https://fanhousanbu:${{secrets.GITHUB_TOKEN}}@github.com/go-to-cloud/go-to-cloud-press.git  master:gh-pages
